<a href="https://colab.research.google.com/github/dhruvpatel45/ML/blob/main/taxis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as snb

In [3]:
df=snb.get_dataset_names()
df

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
ds=snb.load_dataset('taxis')
print(ds)

                  pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0

In [5]:
import pandas as pd
ds['total'].fillna(ds['total'].mean(),inplace=True)

<ipython-input-5-d6a82ae41a8e>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['total'].fillna(ds['total'].mean(),inplace=True)


In [6]:
print(ds)

                  pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0

In [7]:
ds.isna().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [9]:
x=ds.iloc[:,1:]
y=ds.iloc[:,:1]
print(x)
print(y)

                 dropoff  passengers  distance  fare   tip  tolls  total  \
0    2019-03-23 20:27:24           1      1.60   7.0  2.15    0.0  12.95   
1    2019-03-04 16:19:00           1      0.79   5.0  0.00    0.0   9.30   
2    2019-03-27 18:00:25           1      1.37   7.5  2.36    0.0  14.16   
3    2019-03-10 01:49:51           1      7.70  27.0  6.15    0.0  36.95   
4    2019-03-30 13:37:14           3      2.16   9.0  1.10    0.0  13.40   
...                  ...         ...       ...   ...   ...    ...    ...   
6428 2019-03-31 09:55:27           1      0.75   4.5  1.06    0.0   6.36   
6429 2019-03-31 18:34:23           1     18.74  58.0  0.00    0.0  58.80   
6430 2019-03-23 23:14:25           1      4.14  16.0  0.00    0.0  17.30   
6431 2019-03-04 10:14:29           1      1.12   6.0  0.00    0.0   6.80   
6432 2019-03-13 19:48:02           1      3.85  15.0  3.36    0.0  20.16   

       color      payment            pickup_zone  \
0     yellow  credit card        Le

In [14]:
from sklearn.preprocessing import LabelEncoder
lk = LabelEncoder()
y = lk.fit_transform(y.ravel())
print(y)


[4849  699 5520 ... 4875  653 2710]


In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_test)

                 dropoff  passengers  distance  fare    tip  tolls  total  \
363  2019-03-08 22:22:07           1      3.80  15.0   3.75   0.00  22.55   
892  2019-03-01 14:39:12           0      2.30  12.5   1.20   0.00  17.00   
1601 2019-03-23 12:17:24           2      1.30   8.5   0.00   0.00  11.80   
5240 2019-03-18 20:56:37           1      3.68  12.5   0.00   0.00  16.30   
4917 2019-03-04 09:12:57           1     16.30  52.0  12.20   5.76  73.26   
...                  ...         ...       ...   ...    ...    ...    ...   
1406 2019-03-17 21:43:21           1     18.20  52.0   0.00   5.76  61.06   
4281 2019-03-18 23:38:00           1      2.10   9.0   2.06   0.00  12.36   
4791 2019-03-22 15:10:46           1      0.50   4.5   0.00   0.00   7.80   
2505 2019-03-21 23:05:37           1      2.30  11.0   2.95   0.00  17.75   
2016 2019-03-18 20:17:16           2      7.03  22.0   0.00   0.00  23.80   

       color      payment                   pickup_zone  \
363   yellow  cr

In [16]:
print(x_train)

                 dropoff  passengers  distance  fare   tip  tolls  total  \
4986 2019-03-26 09:51:28           2      0.60   5.5  2.20    0.0  11.00   
3744 2019-03-16 01:00:04           1     11.57  38.0  0.00    0.0  41.80   
2102 2019-03-03 10:57:09           1      5.00  19.5  0.00    0.0  22.80   
2461 2019-03-31 14:35:54           4      1.30   7.5  1.62    0.0  12.42   
3087 2019-03-22 01:30:05           1      2.30  10.0  2.76    0.0  16.56   
...                  ...         ...       ...   ...   ...    ...    ...   
4482 2019-03-20 00:00:00           1      1.70   9.5  2.65    0.0  15.95   
1928 2019-03-21 19:54:31           1      2.80  11.0  4.55    0.0  19.85   
246  2019-03-14 19:52:41           1      1.65  11.5  3.95    0.0  19.75   
6077 2019-03-21 19:29:36           1      1.86   9.0  0.00    0.0  10.80   
3044 2019-03-12 11:51:42           1      1.90  14.0  3.45    0.0  20.75   

       color      payment                    pickup_zone  \
4986  yellow  credit card  

In [17]:
print(x_train)

                 dropoff  passengers  distance  fare   tip  tolls  total  \
4986 2019-03-26 09:51:28           2      0.60   5.5  2.20    0.0  11.00   
3744 2019-03-16 01:00:04           1     11.57  38.0  0.00    0.0  41.80   
2102 2019-03-03 10:57:09           1      5.00  19.5  0.00    0.0  22.80   
2461 2019-03-31 14:35:54           4      1.30   7.5  1.62    0.0  12.42   
3087 2019-03-22 01:30:05           1      2.30  10.0  2.76    0.0  16.56   
...                  ...         ...       ...   ...   ...    ...    ...   
4482 2019-03-20 00:00:00           1      1.70   9.5  2.65    0.0  15.95   
1928 2019-03-21 19:54:31           1      2.80  11.0  4.55    0.0  19.85   
246  2019-03-14 19:52:41           1      1.65  11.5  3.95    0.0  19.75   
6077 2019-03-21 19:29:36           1      1.86   9.0  0.00    0.0  10.80   
3044 2019-03-12 11:51:42           1      1.90  14.0  3.45    0.0  20.75   

       color      payment                    pickup_zone  \
4986  yellow  credit card  

In [18]:
print(x_train)

                 dropoff  passengers  distance  fare   tip  tolls  total  \
4986 2019-03-26 09:51:28           2      0.60   5.5  2.20    0.0  11.00   
3744 2019-03-16 01:00:04           1     11.57  38.0  0.00    0.0  41.80   
2102 2019-03-03 10:57:09           1      5.00  19.5  0.00    0.0  22.80   
2461 2019-03-31 14:35:54           4      1.30   7.5  1.62    0.0  12.42   
3087 2019-03-22 01:30:05           1      2.30  10.0  2.76    0.0  16.56   
...                  ...         ...       ...   ...   ...    ...    ...   
4482 2019-03-20 00:00:00           1      1.70   9.5  2.65    0.0  15.95   
1928 2019-03-21 19:54:31           1      2.80  11.0  4.55    0.0  19.85   
246  2019-03-14 19:52:41           1      1.65  11.5  3.95    0.0  19.75   
6077 2019-03-21 19:29:36           1      1.86   9.0  0.00    0.0  10.80   
3044 2019-03-12 11:51:42           1      1.90  14.0  3.45    0.0  20.75   

       color      payment                    pickup_zone  \
4986  yellow  credit card  

In [19]:
print(y_train)

[5227 3234  504 ... 2982 4388 2383]


In [37]:
import numpy as np

In [31]:
print(x_train.dtypes)
print(x_test.dtypes)


dropoff            datetime64[ns]
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                      object
payment                    object
pickup_zone                object
dropoff_zone               object
pickup_borough             object
dropoff_borough            object
dtype: object
dropoff            datetime64[ns]
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                      object
payment                    object
pickup_zone                object
dropoff_zone               object
pickup_borough             object
dropoff_borough            object
dtype: object


In [43]:
print("x_train columns:", x_train.columns)
print("x_test columns:", x_test.columns)
columns_to_encode = ['pickup_zone', 'dropoff_zone', 'pickup_borough', 'dropoff_borough']
columns_in_train = [col for col in columns_to_encode if col in x_train.columns]
columns_in_test = [col for col in columns_to_encode if col in x_test.columns]
x_train = pd.get_dummies(x_train, columns=columns_in_train, drop_first=True)
x_test = pd.get_dummies(x_test, columns=columns_in_test, drop_first=True)
x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)
print("x_train columns after alignment:", x_train.columns)
print("x_test columns after alignment:", x_test.columns)



x_train columns: Index(['dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls', 'total',
       'color', 'payment', 'pickup_zone_Alphabet City',
       ...
       'dropoff_zone_World Trade Center', 'dropoff_zone_Yorkville East',
       'dropoff_zone_Yorkville West', 'pickup_borough_Brooklyn',
       'pickup_borough_Manhattan', 'pickup_borough_Queens',
       'dropoff_borough_Brooklyn', 'dropoff_borough_Manhattan',
       'dropoff_borough_Queens', 'dropoff_borough_Staten Island'],
      dtype='object', length=398)
x_test columns: Index(['dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls', 'total',
       'color', 'payment', 'pickup_zone_Alphabet City',
       ...
       'dropoff_zone_World Trade Center', 'dropoff_zone_Yorkville East',
       'dropoff_zone_Yorkville West', 'pickup_borough_Brooklyn',
       'pickup_borough_Manhattan', 'pickup_borough_Queens',
       'dropoff_borough_Brooklyn', 'dropoff_borough_Manhattan',
       'dropoff_borough_Queens', 'dropoff_borough_Stat

In [46]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
pl_model = lr.fit(x_train, y_train)
prediction = pl_model.predict(x_test)
print(prediction)

[1609.18705548   86.23305423 4709.29410591 ... 4490.37032602 4335.3995545
 3729.95175922]


In [47]:
print(y_test)

[1692   97 4751 ... 4572 4439 3758]


In [48]:
from sklearn.metrics import r2_score
r2_score(y_test,prediction)

0.998161619952537